import React from 'react'

const Terms = () => {
    return (
        <>
            <section id="about" className="about section-bg">
                <div className="container" data-aos="fade-up">
                    <div className="section-title">
                        <h3><span>Terms and Conditions</span></h3>
                    </div>
                    <div className="row">
                        <div className="col-12">
                            <p className="share-tech">
                                365 Space Project NFT is an Ethereum Non-Fungible-Token running on the Ethereum network. Users are completely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. As well, the 365 Space Project Dev Team has no ability to undo, reverse, or restore any of your own private transactions. This website and its connected services are provided “as it is” and without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions you conduct. By interacting with the 365 Space Project website, Ethereum contract & minting mechanism, you take full responsibility for any and all transactions & results.
                            </p>
                            <p className="blue-text">Ownership</p>
                            <p className="share-tech">a). Each 365 Space Project NFT is a unique Non-Fungible-Token running on the Ethereum blockchain. When you purchase a 365 Space Project NFT, you own the NFT, ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network. </p>
                            <p className="share-tech">b). Personal Use. Subject to your continued compliance with these Terms, SIM LLC grants you a worldwide, royalty-free license to use, copy, and display the purchased Art & NFT, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your 365 Space Project NFT.
                            </p>
                            <p className="share-tech">
                                c). Commercial Use. Subject to your continued compliance with these Terms, SIM LLC grants you an unlimited, worldwide license to use, copy, and display the purchased NFT for the purpose of creating derivative works based upon the Art (“Commercial Use”).
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Terms
